name: Run Dagger Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dagger:
    name: Dagger Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.4
          cache: false
      
      - name: Run Pipeline
        uses: dagger/dagger-for-github@v6
        with:
          workdir: .
          verb: run
          args: go run pipeline.go
          version: "0.13.7"
